name: file_picker_macos
description: MacOS implementation of the location plugin
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
version: 5.0.0-dev.3

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: location
    platforms:
      macos:
        dartPluginClass: FilePickerMacOS

dependencies:
  flutter:
    sdk: flutter
  file_picker_platform_interface:
    git:
      url: https://github.com/Eu-Arthur/flutter_file_picker_platform_interface.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
